# Generated by Django 5.2.6 on 2025-09-22 14:12

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("embedding", pgvector.django.vector.VectorField(dimensions=384)),
                ("file", models.FileField(upload_to="documents/")),
            ],
        ),
    ]
