# Generated by Django 5.2.6 on 2025-09-22 15:17

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="documents/"),
                ),
                ("embedding", pgvector.django.vector.VectorField(dimensions=384)),
                ("source", models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name="Document",
        ),
    ]
